fixes3

diff --git a/.github/workflows/school.yml b/.github/workflows/school.yml
--- a/.github/workflows/school.yml
+++ b/.github/workflows/school.yml
@@ -9,9 +9,9 @@ jobs:
   run:
     runs-on: ubuntu-latest
 
-    # <<< ВАЖНО: поменяй имя файла на свой токен из папки tokens >>>
+    # <<< ВАЖНО: укажи точное имя токена из папки tokens >>>
     env:
-      GMAIL_TOKEN_FILENAME: token_forschoolcalendar_at_gmail.com.pkl
+      GMAIL_TOKEN_FILENAME: token_skidlineg_at_gmail.com.pkl
 
     steps:
       - name: Checkout
@@ -55,8 +55,8 @@ jobs:
           GMAIL_TOKEN_B64: ${{ secrets.GMAIL_TOKEN_B64 }}
         run: |
           mkdir -p tokens
-          echo "$GMAIL_TOKEN_B64" | base64 -d > "tokens/${token_skidlineg_at_gmail.com.pkl}"
-          test -s "tokens/${token_skidlineg_at_gmail.com.pkl}" || { echo "::error::gmail token is empty"; exit 1; }
+          echo "$GMAIL_TOKEN_B64" | base64 -d > "tokens/${GMAIL_TOKEN_FILENAME}"
+          test -s "tokens/${GMAIL_TOKEN_FILENAME}" || { echo "::error::gmail token is empty"; exit 1; }
           ls -la tokens
 
       - name: Run script
